### PR TITLE
Disable colors

### PR DESCRIPTION
**Pull request by umputun**
Add support of b/w output without colorization per host. The new param is `--no-color`. 

The change was way too complicated for such a simple functionality because of the tight coupling between the core parts and the logger. I have refactored logging support and made it injectable.

### CODE REVIEW

**Comment by knutov** [comment]
Something possible goes wrong, after this PR:

```

tasks:
  - name: print
    commands:
      - name: print
        echo: "hello world"

spot -p test.yml -t s2 --task print

spot v1.10.1-9aab799-2023-07-27T15:02:00Z
[s2 s2.xxxxxxxx:22] run task "print", commands: 1
[s2 s2.xxxxxxxx:22] completed command "print" {echo: hello world} (501ms)
[s2 s2.xxxxxxxx:22] completed task "print", commands: 1 (760ms)

spot v1.11.0-b97d854-2023-08-08T04:02:08Z
# <--- now any output here with this task
```

**Comment by iRay** [comment]
Seems some regression appeared once again.
Installed spot with `brew`.
Created a simple task the same like the one above.

```yml
tasks:
  - name: print
    commands:
      - name: print
        echo: "hello world"
```

Run with: `spot -p spot.yml -t prod`
Getting the next output:

```shell
spot v1.12.0-b327c23-2023-11-13T20:20:26Z
[104.236.64.105:22] run task "print", commands: 1
[104.236.64.105:22] completed command "print" {echo: hello world} (497ms)
[104.236.64.105:22] completed task "print", commands: 1 (1.444s)
```

All colors are "red". Thought it was something with term color scheme. Changed scheme, but everything remains the same in red colors.
Tried to execute `ls -la` on the remote system - no output.
After adding verbose with `-v` param I can see directory listing of the remote host.

Just in case uninstalled spot with `brew` and installed it with `go install` - the same behaviour.
Tried to run with `--dbg` to see if something is wrong, but with no luck. Everything looks fine.

System: `MBP M1, macOS: Sonoma 14.1.1 (23B81)`
P.S.
Verbose output:
```shell
spot v1.12.0-b327c23-2023-11-13T20:20:26Z
[104.236.64.105:22] run task "print", commands: 1
[104.236.64.105:22] run command "print"
[104.236.64.105:22]  > echo "hello world"
[104.236.64.105:22]  > hello world
[104.236.64.105:22] completed command "print" {echo: hello world} (1.235s)
[104.236.64.105:22] completed task "print", commands: 1 (2.189s)
```

**Comment by umputun** [comment]
i can't reproduce "same color issue"  with neither brew version or the current master

image

> Tried to execute ls -la on the remote system - no output.
> After adding verbose with -v param I can see directory listing of the remote host.

This is how it suppose to work, not sure what the issue here.

**Comment by iRay** [comment]
I didn’t see output for `ls` command for the remote host (only with `-v` flag) and output was in red so it confused me.
With `hostColorizer` method now everything is clear,  thank you!

**Pull request merged**
